version: '3'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    links:
      - mysql:db
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - 8889:3306
    volumes:
      - ./e_primelec.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: e_primelec
      MYSQL_USER: user
      MYSQL_PASSWORD: password
